# Project
site_name: OpenCossan
site_description: OpenCossan is an open and free toolbox for uncertainty quantification and management.

# Copyright
copyright: Copyright &copy; 2020 Cossan Working Group

# Repository
repo_name: OpenCossan
repo_url: https://github.com/cossan-working-group/OpenCossan

# Theming
theme:
  name: material
  language: en

# Extensions
markdown_extensions:
  - attr_list
  - admonition
  - codehilite

# Plugins
plugins:
  - search
  - awesome-pages